services:
  - type: web
    name: job-hunter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: JOOBLE_API_KEY
        sync: false
